version: '3.8'

services:
  postgres:
    environment:
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    volumes:
      - ./scripts/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./logs:/workspace/logs

  pgadmin:
    environment:
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False
      - PGADMIN_CONFIG_LOGIN_BANNER="Welcome to Recursive CTE Examples!"
    volumes:
      - ./scripts/pgadmin-servers.json:/pgadmin4/servers.json:ro 